name: closr_chat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firestore_ui: ^1.2.0
  cloud_firestore: ^0.9.5+2
  flutter_signin_button: ^0.2.6
  firebase_database: ^2.0.1+1
  google_sign_in: ^4.0.1+1
  firebase_auth: ^0.8.1+1
  firebase_storage: ^2.0.1+1
  http: ^0.12.0+1
  image_picker: ^0.5.0+3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

